[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Static export configuration for Next.js
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
