[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Static export configuration for Next.js
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Form handling and notifications
[[forms]]
  name = "contact"

# Form notifications - send to email
[[forms]]
  name = "contact"
  action = "/contact-success"
  
  # Email notification settings
  [forms.settings]
    to = "bookings@lucyscotthair.co.uk"
    subject = "New Booking Enquiry - Lucy Scott Hair"
    from = "Lucy Scott Hair <noreply@lucyscotthair.co.uk>"
    
  # Custom email template
  [forms.notification]
    type = "email"
    to = "bookings@lucyscotthair.co.uk"
  
# Headers for security and form handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
